version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.1-openjdk-19-slim
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"
    steps:
      - checkout
      - run: mvn clean install
      - store_artifacts:
          path: target
          destination: target

  test:
    docker:
      - image: maven:3.8.1-openjdk-19-slim
    steps:
      - checkout
      - run: mvn test -e

  build-docker-image:
    docker:
      - image: circleci/openjdk:19-jdk
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t my-app .
      - run:
          name: Push Docker Image
          command: docker push my-app

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker-image:
          requires:
            - test