version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.1-openjdk-19-slim
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"
    steps:
      - checkout
      - run: mvn clean install
        command:
          echo 'Hello World - Test FoodOrder-Buddy Pipeline'
      - store_artifacts:
          path: target
          destination: target

  test:
    docker:
      - image: maven:3.8.1-openjdk-19-slim
    steps:
      - checkout
      - run: mvn test -e

  build-docker-image:
    docker:


workflows:
  version: 2
  build-and-test:
    jobs:
      - build